# https://blog.openshift.com/openshift-pipelines-jenkins-blue-ocean/
# https://github.com/siamaksade/cart-service/blob/master/openshift/cart-pipeline.yaml
# https://github.com/siamaksade/openshift-cd-demo
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "example-pipeline", "namespace": "", "kind": "DeploymentConfig"}]'
  name: example-pipeline # {project_name}
spec:
  source:
    git:
      ref: master # {branch_name} - Jenkinsfile must be present
      uri: git@github.com:RBlaine95/DevopsDay-Practice.git # {git_url_ssh_clone}
    sourceSecret:
      name: git-deploy-key
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile # Jenkinsfile directory relative to project root - CASE SENSITIVE
  triggers:
  - github:
      secret: supersecretplaintextwebhook # https://docs.okd.io/latest/dev_guide/builds/triggering_builds.html#github-webhooks
    type: GitHub
